
		inicializarlibro(1, "To Kill a Mockingbird", "Harper Lee", 15.99, FICCION, 10);
		inicializarlibro(2, "1984", "George Orwell", 12.49, FICCION, 5);
		inicializarlibro(3, "The Great Gatsby", "F. Scott Fitzgerald", 10.99, FICCION, 8);
		inicializarlibro(4, "Moby Dick", "Herman Melville", 18.99, FICCION, 12);
		inicializarlibro(5, "War and Peace", "Leo Tolstoy", 20.00, FICCION, 7);
		inicializarlibro(6, "Pride and Prejudice", "Jane Austen", 14.99, FICCION, 9);
		inicializarlibro(7, "The Catcher in the Rye", "J.D. Salinger", 10.00, FICCION, 6);
		inicializarlibro(8, "The Odyssey", "Homer", 17.49, FICCION, 4);
		inicializarlibro(9, "Ulysses", "James Joyce", 25.00, FICCION, 2);
		inicializarlibro(10, "The Divine Comedy", "Dante Alighieri", 22.00, POESIA, 3);
		inicializarlibro(11, "Leaves of Grass", "Walt Whitman", 13.00, POESIA, 11);
		inicializarlibro(12, "The Iliad", "Homer", 18.50, FICCION, 7);
		inicializarlibro(13, "A Brief History of Time", "Stephen Hawking", 15.00, NO_FICCION, 15);
		inicializarlibro(14, "The Art of War", "Sun Tzu", 9.99, NO_FICCION, 20);
		inicializarlibro(15, "Sapiens: A Brief History of Humankind", "Yuval Noah Harari", 16.49, NO_FICCION, 13);
		inicializarlibro(16, "The Selfish Gene", "Richard Dawkins", 14.00, NO_FICCION, 6);
		inicializarlibro(17, "The Road to Serfdom", "F.A. Hayek", 10.50, NO_FICCION, 5);
		inicializarlibro(18, "The Wealth of Nations", "Adam Smith", 30.00, NO_FICCION, 8);
		inicializarlibro(19, "On the Origin of Species", "Charles Darwin", 24.99, NO_FICCION, 4);
		inicializarlibro(20, "The Prince", "Niccolò Machiavelli", 8.99, NO_FICCION, 14);
		inicializarlibro(21, "Hamlet", "William Shakespeare", 11.50, TEATRO, 6);
		inicializarlibro(22, "Macbeth", "William Shakespeare", 9.50, TEATRO, 8);
		inicializarlibro(23, "Othello", "William Shakespeare", 10.99, TEATRO, 7);
		inicializarlibro(24, "A Doll's House", "Henrik Ibsen", 12.50, TEATRO, 5);
		inicializarlibro(25, "Waiting for Godot", "Samuel Beckett", 13.99, TEATRO, 4);
		inicializarlibro(26, "Death of a Salesman", "Arthur Miller", 14.99, TEATRO, 10);
		inicializarlibro(27, "The Glass Menagerie", "Tennessee Williams", 11.00, TEATRO, 9);
		inicializarlibro(28, "Long Day's Journey into Night", "Eugene O'Neill", 19.50, TEATRO, 3);
		inicializarlibro(29, "The Importance of Being Earnest", "Oscar Wilde", 8.50, TEATRO, 15);
		inicializarlibro(30, "The Waste Land", "T.S. Eliot", 6.99, POESIA, 10);
		inicializarlibro(31, "Paradise Lost", "John Milton", 12.00, POESIA, 7);
		inicializarlibro(32, "Beowulf", "Anonymous", 15.00, POESIA, 5);
		inicializarlibro(33, "Essays", "Michel de Montaigne", 20.00, ENSAYO, 4);
		inicializarlibro(34, "Self-Reliance and Other Essays", "Ralph Waldo Emerson", 9.00, ENSAYO, 9);
		inicializarlibro(35, "Civil Disobedience and Other Essays", "Henry David Thoreau", 7.50, ENSAYO, 11);
		inicializarlibro(36, "Meditations", "Marcus Aurelius", 11.99, ENSAYO, 8);
		inicializarlibro(37, "The Federalist Papers", "Alexander Hamilton, James Madison, John Jay", 18.00, ENSAYO, 5);
		inicializarlibro(38, "The Communist Manifesto", "Karl Marx and Friedrich Engels", 5.99, ENSAYO, 12);
		inicializarlibro(39, "The Republic", "Plato", 16.00, ENSAYO, 6);
		inicializarlibro(40, "Thus Spoke Zarathustra", "Friedrich Nietzsche", 14.99, ENSAYO, 10);